# Generated by Django 2.2.3 on 2019-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='process_list',
            field=models.ManyToManyField(to='FinalProduct.Process'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='Material',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='Model_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='Part_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='components',
            name='type_of_production',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
