# Generated by Django 2.2.3 on 2019-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0002_auto_20190702_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('Material_type', models.CharField(default='', max_length=50)),
                ('Primary_Stock_Unit', models.CharField(default='', max_length=50)),
                ('Unit_type', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField()),
                ('Rawmaterial_list', models.ManyToManyField(to='FinalProduct.Components')),
            ],
        ),
    ]
