# Generated by Django 2.2.3 on 2019-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0003_rawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
