# Generated by Django 2.2.3 on 2019-07-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0004_auto_20190709_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='Rawmaterial_list',
        ),
        migrations.AddField(
            model_name='components',
            name='Rawmaterial_list',
            field=models.ManyToManyField(to='FinalProduct.RawMaterial'),
        ),
    ]
