# Generated by Django 2.2.3 on 2019-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0005_auto_20190709_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial_Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('Component_Name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
