# Generated by Django 2.2.3 on 2019-07-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0006_rawmaterial_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
