# Generated by Django 2.2.3 on 2019-07-16 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0008_components_cheack_for_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='Cheack_for_Allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='components',
            name='Rawmaterial_list',
        ),
        migrations.AddField(
            model_name='components',
            name='Rawmaterial_list',
            field=jsonfield.fields.JSONField(default=datetime.datetime(2019, 7, 16, 10, 2, 59, 44223, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
