# Generated by Django 2.2.3 on 2019-07-19 11:43

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0009_auto_20190716_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='Process_list',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
