# Generated by Django 2.2.3 on 2019-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProduct', '0013_auto_20190727_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='In_DataBase',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='Model_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='Part_name',
            field=models.CharField(default='Components-', max_length=50),
        ),
        migrations.AlterField(
            model_name='components',
            name='type_of_production',
            field=models.CharField(default='In House', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='Customer-', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='name',
            field=models.CharField(default='PO-', max_length=50),
        ),
    ]
